
language: objective-c
osx_image: xcode11

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:

    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail
    - xcodebuild clean build -project Stacker.xcodeproj -target 'Stacker' -sdk iphonesimulator -configuration Debug | xcpretty